name: VM Manager Release

on:
  release:
    types: [published, edited]
permissions: write-all
jobs:
  build_ubuntu_gcc:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
        with:
          path: vm-manager
          fetch-depth: 0

      - name: setup
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes make devscripts lintian debhelper
          sudo apt-get --quiet install --yes autoconf libtool pkg-config 

      - name: Set release version
        run: echo "REL_VER=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: build
        run: |
          export PATH="${{ env.LOCAL_INSTALL_DIR }}/bin:$PATH"
          sudo ln -s $(which cmake) /usr/bin/cmake || echo ""
          cd vm-manager/
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          debuild --preserve-env -b -uc -us --lintian-opts --profile debian
          cp $(realpath ../*.deb) vm-manager_${{ env.REL_VER }}.deb

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vm-manager.${{ matrix.os }}.${{ github.run_id }}.${{ github.sha }}
          path: |
            vm-manager/debian/
            *.deb
            *.ddeb
            *.build
            *.buildinfo
            *.changes

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vm-manager/vm-manager_${{ env.REL_VER }}.deb
