name: Lint Code Base

on: [push, pull_request]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: superlint
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_CPP: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
